// Address-related words to add to compromise lexicon

export default {
  // Street types
  street: 'StreetType',
  avenue: 'StreetType',
  road: 'StreetType',
  boulevard: 'StreetType',
  drive: 'StreetType',
  lane: 'StreetType',
  way: 'StreetType',
  court: 'StreetType',
  place: 'StreetType',
  circle: 'StreetType',
  parkway: 'StreetType',
  highway: 'StreetType',
  route: 'StreetType',
  terrace: 'StreetType',
  close: 'StreetType',
  crescent: 'StreetType',
  grove: 'StreetType',
  walk: 'StreetType',
  rise: 'StreetType',
  // Abbreviations
  st: 'StreetType',
  ave: 'StreetType',
  rd: 'StreetType',
  blvd: 'StreetType',
  dr: 'StreetType',
  ln: 'StreetType',
  ct: 'StreetType',
  pl: 'StreetType',
  pkwy: 'StreetType',
  hwy: 'StreetType',
  // Unit types
  apartment: 'UnitType',
  apt: 'UnitType',
  suite: 'UnitType',
  ste: 'UnitType',
  unit: 'UnitType',
  flat: 'UnitType',
  floor: 'UnitType',
  building: 'UnitType',
  bldg: 'UnitType',
  // Directional
  north: 'Direction',
  south: 'Direction',
  east: 'Direction',
  west: 'Direction',
  northeast: 'Direction',
  northwest: 'Direction',
  southeast: 'Direction',
  southwest: 'Direction',
  n: 'Direction',
  s: 'Direction',
  e: 'Direction',
  w: 'Direction',
  ne: 'Direction',
  nw: 'Direction',
  se: 'Direction',
  sw: 'Direction'
}
